### ISSUE TITLE
public code for GTEx web services?

### ISSUE THREAD

**Issue by nmra-cwilks** [broadinstitute/expressMap#226]
Hi,

Thanks for making publicly available this valuable set of tools/code from the GTEx project.

We're interested in setting up our own version for internal use/data and we're curious if the code for the RESTful web services component(s) was also available publicly?

I saw that https://github.com/broadinstitute/gtex-public exists but it only lists the web services definition themselves rather than the actual web services code for the backend.

Thanks in advance,
Chris

**Comment by jnedzel** [comment]
Hi Chris:

No, the server-side code is not open source.  The server architecture is somewhat complex, with files in Google Cloud Storage, web services running in Google App Engine and Kubernetes, and about 1T of data in ~50 collections in MongoDB (along with all the ETL scripts to load those collections).  It just isn't feasible for us to document how to implement and load an instance.

Sincerely,

Jared Nedzel

**Comment by nmra-cwilks** [comment]
Thanks @jnedzel for the quick response.  
I completely understand about not making the server side public.
