### ISSUE TITLE
clustering package used in the expression heatmap?

### ISSUE THREAD

**Issue by nmra-cwilks** [broadinstitute/expressMap#227]
Hi,

These are great tools and we're very grateful you folks open sourced the visualization code!
Is it possible to find out what package/program was used to produce the clustering of the genes and tissues in the GTEx gene expression heatmap display?
The description says "hierarchically clustered using the Euclidean distance and average linkage method" but it'd be super helpful to also know the specific package/program used (or at least the output format of the clustering) as we may want to cluster our data in the same way.

Thanks in advance,
Chris

**Comment by kataviz** [comment]
Hi Chris,

Thank you for reaching out. The clustering is done using SciPy on the server side, via a Restful API call. The visualization does not have the functionality of clustering, it simply parses and displays the dendrogram. Hope this helps. 

Thanks,
Katherine Huang

**Comment by nmra-cwilks** [comment]
thanks for the quick response!
